ln -sf ~/.dotfiles/alacritty/alacritty.yml ~/.alacritty.yml
ln -sf ~/.dotfiles/alacritty/alacritty.toml ~/.alacritty.toml
ln -sf ~/.dotfiles/bash/bashrc ~/.bashrc
ln -sf ~/.dotfiles/i3/config ~/.config/i3/config
ln -sf ~/.dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/.dotfiles/picom ~/.config/picom
ln -sf ~/.dotfiles/polybar ~/.config/polybar
ln -sf ~/.dotfiles/rofi ~/.config/rofi
ln -sf ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
ln -sf ~/.dotfiles/vim/vimrc ~/.vimrc
ln -sf ~/.dotfiles/zsh/aliases ~/.aliases
ln -sf ~/.dotfiles/zsh/zshrc ~/.zshrc
